Coc
cacrespo/django_tyv pull request #13
Opened 2021-08-28 20:06 UTC by jsanchez23

2021-08-29 00:19 UTC, cacrespo commented
Muchas gracias @jsanchez23 ! Te dejé algunos pedidos para ajustar. Creo que sería bueno que el resto del equipo valide también el código antes de hacer el merge.
@gianfranco-s @guillermo-k

2021-08-29 00:22 UTC, cacrespo requested changes

2021-08-29 00:22 UTC, cacrespo commented on CODE_OF_CONDUCT.md
> +#Este es nuestro código de conducta
Al no tener el espacio no tomaba correctamente el formato del título.
```suggestion
# Este es nuestro código de conducta
```

2021-08-29 00:22 UTC, cacrespo commented on CODE_OF_CONDUCT.md
> +2) Recordar que todos tienen una vida ademas del proyecto, respetarla.
Estos dos puntos me parece que son muy parecidos. ¿Qué te parece si los juntamos?

2021-08-29 00:22 UTC, cacrespo commented on CODE_OF_CONDUCT.md
> +5) A disfrutar que la vida es corta
Cuánta verdad!!! 😄 
```suggestion
5) A disfrutar que la vida es corta!!! 🥳
```

2021-08-29 04:40 UTC, gianfranco-s approved these changes
Estoy de acuerdo con el COC, y con los cambios de @cacrespo

2021-08-29 11:43 UTC, guillermo-k commented on CODE_OF_CONDUCT.md
> +2) Recordar que todos tienen una vida ademas del proyecto, respetarla.
Yo creo que esta bien como esta. A lo sumo se puede juntar de la siguiente manera
respeto mutuo, sin olvidar que todos tienen una vida además del proyecto.

2021-08-29 11:48 UTC, guillermo-k commented on CODE_OF_CONDUCT.md
> +4) El código se puede renovar o actualizar si los miembros están de acuerdo.
Que les parece cambiarlo por:
Los cambios deberán ser sometidos a revisión antes de realizar el merge.?

2021-08-29 12:02 UTC, guillermo-k requested changes

2021-08-29 12:02 UTC, guillermo-k commented on CODE_OF_CONDUCT.md
> +4) El código se puede renovar o actualizar si los miembros están de acuerdo.
```suggestion
4) Los cambios deberán ser sometidos a revisión antes de realizar el merge.
```

2021-08-29 12:11 UTC, guillermo-k approved these changes

2021-09-03 23:56 UTC, merged

2021-09-03 23:58 UTC, cacrespo commented
Mergeo más allá del feedback así vamos cerrando issues. 
@jsanchez23  @cothey si le parece conveniente agregar o cambiar algo abran otro PR.

closes #11