Probando rama
cacrespo/django_tyv pull request #18
Opened 2021-08-30 20:11 UTC by guillermo-k

creacion de 2 apps: categorias y productos
actualizacion de requirements

2021-08-31 11:16 UTC, cacrespo requested changes
Van algunas sugerencias.
`requirements.txt` me figura como archivo binario ¿? ¿le hiciste algo puntual a ese archivo?

2021-08-31 11:16 UTC, cacrespo commented on django_tyv/categorias/admin.py
> +# Register your models here.
Mejor quitemos esos comentarios que no aportan mucho.
```suggestion
```

2021-08-31 11:16 UTC, cacrespo commented on django_tyv/categorias/migrations/0001_initial.py
> +# Generated by Django 3.2.6 on 2021-08-30 15:03
```suggestion
```

2021-08-31 11:16 UTC, cacrespo commented on django_tyv/categorias/models.py
> +# Create your models here.
```suggestion
```

2021-08-31 11:16 UTC, cacrespo commented on django_tyv/categorias/tests.py
> +# Create your tests here.
Quito la linea y además comento: esto de los tests es un tema super importante. Deberíamos profundizar en el tema.
```suggestion
```

2021-08-31 11:16 UTC, cacrespo commented on django_tyv/categorias/views.py
> +# Create your views here.
```suggestion
```

2021-08-31 11:16 UTC, cacrespo commented on django_tyv/productos/admin.py
> +# Register your models here.
```suggestion
```

2021-08-31 11:16 UTC, cacrespo commented on django_tyv/productos/migrations/0001_initial.py
> +# Generated by Django 3.2.6 on 2021-08-30 15:42
```suggestion
```

2021-08-31 11:16 UTC, cacrespo commented on django_tyv/productos/models.py
> +# Create your models here.
```suggestion
```

2021-08-31 11:16 UTC, cacrespo commented on django_tyv/productos/tests.py
> +# Create your tests here.
```suggestion
```

2021-08-31 11:16 UTC, cacrespo commented on django_tyv/productos/views.py
> +# Create your views here.
```suggestion
```

2021-09-03 19:22 UTC, guillermo-k commented on django_tyv/categorias/admin.py
> +# Register your models here.
A requirements no le hice nada mas que una incorporación de (Pillow) en la terminal me salto el mensaje de que era necesario para el manejo de las fotos.(El requirements que tengo local, lo abro sin problemas.

los comentarios no los borre, para que me quedaran a la vista, en si, no tenia pensado hacer el commit que hice, esta todo muy a medias, era algo que tenia, pero como Carlos me dijo de subirlo, lo hice.

2021-09-03 19:52 UTC, gianfranco-s commented
¿Por qué hay una clase Categoría por fuera de Producto?
¿No debería ser la categoría un atributo de Producto?

2021-09-03 20:24 UTC, gianfranco-s commented
En el chat de Telegram, esta fue la explicación (según la entendí yo):
* Ya hay una categoría dentro de Producto.
* Se busca evitar que el usuario cargue varias categorías similares (pañal o pañales).
* En el front se dará un interfaz diferente para realizar la carga de categorías.

Finalmente, al decir de Guillermo:
"...lo que te da hacerlo en 2 tablas es que siempre te queden guardadas todas las categorias, como decis vos, si por ejemplo tenes un solo producto en "chupetes", lo borras por x motivo, cuando cargues un chupete, tenes que crear una nueva categoria.
y otra es que le podes agregar una descripcion a la categoria, por decir: Pñales en todos los talle......"

2021-09-03 20:27 UTC, gianfranco-s approved these changes
Por mi lado, está todo bien. Hay que mirar el tema ese de `requirements.txt`.

Según lo que fuimos charlando en Telegram:
"...si por ejemplo tenes un solo producto en "chupetes", lo borras por x motivo, cuando cargues un chupete, tenes que crear una nueva categoria.[...]"

2021-09-03 20:55 UTC, cacrespo commented on django_tyv/categorias/admin.py
> +# Register your models here.
@guillermo-k perfecto Guille!
Creo que es mejor que vayamos subiendo pequeñas modificaciones parciales. De ese modo es más fácil revisar.

2021-09-03 20:56 UTC, cacrespo approved these changes

2021-09-03 21:18 UTC, cacrespo approved these changes

2021-09-03 23:57 UTC, closed without merging